-- PharmaCare Pro — Migration 002: Compliance & P0 Gaps
PRAGMA foreign_keys = ON;

-- Narcotic Drug Register (NDPS Act)
CREATE TABLE IF NOT EXISTS narcotic_register (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  entry_date          TEXT    NOT NULL DEFAULT (date('now')),
  bill_id             INTEGER REFERENCES bills(id),
  bill_number         TEXT    NOT NULL DEFAULT '',
  patient_name        TEXT    NOT NULL DEFAULT '',
  patient_address     TEXT    NOT NULL DEFAULT '',
  patient_age         TEXT    NOT NULL DEFAULT '',
  doctor_name         TEXT    NOT NULL DEFAULT '',
  doctor_reg_no       TEXT    NOT NULL DEFAULT '',
  medicine_name       TEXT    NOT NULL,
  medicine_id         INTEGER REFERENCES medicines(id),
  batch_number        TEXT    NOT NULL DEFAULT '',
  quantity_dispensed  REAL    NOT NULL DEFAULT 0,
  unit                TEXT    NOT NULL DEFAULT 'TAB',
  opening_balance     REAL    NOT NULL DEFAULT 0,
  quantity_received   REAL    NOT NULL DEFAULT 0,
  closing_balance     REAL    NOT NULL DEFAULT 0,
  supplier_name       TEXT    NOT NULL DEFAULT '',
  purchase_invoice_no TEXT    NOT NULL DEFAULT '',
  remarks             TEXT    NOT NULL DEFAULT '',
  created_by          INTEGER REFERENCES users(id),
  created_at          TEXT    NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_narc_date ON narcotic_register(entry_date);
CREATE INDEX IF NOT EXISTS idx_narc_bill ON narcotic_register(bill_id);

-- Form 16 / Prescription Register (Schedule H)
CREATE TABLE IF NOT EXISTS prescription_register (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  entry_date      TEXT    NOT NULL DEFAULT (date('now')),
  bill_id         INTEGER REFERENCES bills(id),
  bill_number     TEXT    NOT NULL DEFAULT '',
  patient_name    TEXT    NOT NULL DEFAULT '',
  patient_age     TEXT    NOT NULL DEFAULT '',
  patient_address TEXT    NOT NULL DEFAULT '',
  doctor_name     TEXT    NOT NULL DEFAULT '',
  doctor_reg_no   TEXT    NOT NULL DEFAULT '',
  medicine_name   TEXT    NOT NULL,
  medicine_id     INTEGER REFERENCES medicines(id),
  schedule        TEXT    NOT NULL DEFAULT 'H',
  batch_number    TEXT    NOT NULL DEFAULT '',
  quantity        REAL    NOT NULL DEFAULT 0,
  unit            TEXT    NOT NULL DEFAULT 'TAB',
  remarks         TEXT    NOT NULL DEFAULT '',
  created_by      INTEGER REFERENCES users(id),
  created_at      TEXT    NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_presc_date ON prescription_register(entry_date);
CREATE INDEX IF NOT EXISTS idx_presc_bill ON prescription_register(bill_id);

-- New settings for compliance
INSERT OR IGNORE INTO settings(key,value) VALUES
  ('drug_licence_expiry',        '""'),
  ('fssai_licence_no',           '""'),
  ('fssai_licence_expiry',       '""'),
  ('schedule_x_licence_no',      '""'),
  ('schedule_x_licence_expiry',  '""'),
  ('pharmacy_state_code',        '"27"'),
  ('pharmacy_city',              '""'),
  ('pharmacy_pincode',           '""'),
  ('irp_username',               '""'),
  ('irp_password',               '""'),
  ('irp_app_key',                '""'),
  ('irp_sandbox_mode',           '"true"'),
  ('ewb_username',               '""'),
  ('ewb_password',               '""'),
  ('ewb_sandbox_mode',           '"true"');

-- Drug Interactions: 200 additional pairs (total ~245)
INSERT OR IGNORE INTO drug_interactions(drug1,drug2,severity,description,management) VALUES
('rifampicin','warfarin','major','Rifampicin strongly induces CYP2C9, reducing warfarin levels by 90%.','Increase warfarin dose significantly. Monitor INR weekly during rifampicin therapy.'),
('rifampicin','oral contraceptives','major','Rifampicin induces CYP enzymes, reducing OCP hormone levels — contraceptive failure.','Switch to non-hormonal contraception during and 4 weeks after rifampicin.'),
('rifampicin','phenytoin','major','Rifampicin induces CYP2C9/3A4, reducing phenytoin levels.','Monitor phenytoin levels; dose increase likely needed.'),
('rifampicin','carbamazepine','major','Rifampicin induces carbamazepine metabolism, reducing levels.','Monitor carbamazepine levels and seizure control closely.'),
('rifampicin','fluconazole','major','Rifampicin significantly reduces fluconazole plasma levels.','Increase fluconazole dose; monitor clinical response.'),
('rifampicin','digoxin','major','Rifampicin induces P-glycoprotein, reducing digoxin levels by 50%.','Increase digoxin dose; monitor levels during and after rifampicin.'),
('rifampicin','corticosteroids','major','Rifampicin doubles clearance of corticosteroids.','Double corticosteroid dose during rifampicin therapy.'),
('isoniazid','phenytoin','major','Isoniazid inhibits CYP2C19, raising phenytoin levels — toxicity risk.','Monitor phenytoin levels. Reduce phenytoin dose if needed.'),
('isoniazid','carbamazepine','moderate','Isoniazid inhibits carbamazepine metabolism.','Monitor carbamazepine levels; reduce dose if toxicity signs appear.'),
('isoniazid','paracetamol','moderate','Chronic isoniazid induces CYP2E1, increasing toxic paracetamol metabolite.','Limit paracetamol to 2g/day in patients on isoniazid.'),
('isoniazid','alcohol','major','Both hepatotoxic; combination increases liver damage risk.','Advise complete alcohol abstinence during TB treatment.'),
('ketoconazole','simvastatin','major','Ketoconazole inhibits CYP3A4, raising simvastatin 10-fold — rhabdomyolysis risk.','Contraindicated. Suspend statin during ketoconazole therapy.'),
('itraconazole','simvastatin','major','Itraconazole inhibits CYP3A4, raising simvastatin — rhabdomyolysis.','Contraindicated. Switch to pravastatin or rosuvastatin.'),
('itraconazole','digoxin','major','Itraconazole inhibits P-glycoprotein, raising digoxin levels.','Reduce digoxin dose by 50%. Monitor levels closely.'),
('itraconazole','warfarin','major','Itraconazole inhibits warfarin metabolism.','Reduce warfarin dose. Monitor INR every 2 days.'),
('fluconazole','midazolam','major','Fluconazole markedly increases midazolam levels.','Avoid oral midazolam. Use IV with careful monitoring.'),
('ciprofloxacin','sucralfate','major','Sucralfate reduces ciprofloxacin absorption by 90%.','Give ciprofloxacin at least 6 hours before sucralfate.'),
('levofloxacin','amiodarone','major','Both prolong QT interval — torsades risk.','Avoid combination. Monitor ECG if unavoidable.'),
('erythromycin','simvastatin','major','Erythromycin inhibits CYP3A4, raising simvastatin — rhabdomyolysis.','Suspend statin during erythromycin course.'),
('erythromycin','amiodarone','major','Both prolong QT interval.','Avoid. Risk of life-threatening arrhythmia.'),
('erythromycin','carbamazepine','major','Erythromycin inhibits carbamazepine metabolism — toxicity.','Monitor carbamazepine levels closely.'),
('azithromycin','amiodarone','major','Both prolong QT interval — serious arrhythmia risk.','Avoid. Significant risk of fatal arrhythmia.'),
('metronidazole','alcohol','major','Disulfiram-like reaction: flushing, vomiting, tachycardia.','Strictly no alcohol during and 48 hours after metronidazole.'),
('metronidazole','lithium','moderate','Metronidazole may raise lithium levels.','Monitor lithium levels during co-administration.'),
('cotrimoxazole','warfarin','moderate','Cotrimoxazole inhibits warfarin metabolism.','Monitor INR closely.'),
('amiodarone','warfarin','major','Amiodarone strongly inhibits warfarin metabolism — INR 2-4x baseline.','Reduce warfarin dose by 30-50%; monitor INR weekly for months.'),
('amiodarone','simvastatin','major','Amiodarone inhibits CYP3A4 — simvastatin raises myopathy risk.','Do not exceed simvastatin 20mg; prefer rosuvastatin.'),
('amiodarone','phenytoin','major','Amiodarone raises phenytoin to toxic levels.','Monitor phenytoin levels. Reduce dose as needed.'),
('amiodarone','procainamide','major','Additive QT prolongation — torsades risk.','Avoid combination.'),
('clopidogrel','aspirin','moderate','Additive GI bleeding risk; combination intentional for ACS.','Use PPI (pantoprazole) for GI protection.'),
('diltiazem','simvastatin','major','Diltiazem inhibits CYP3A4, raising simvastatin — rhabdomyolysis.','Do not exceed simvastatin 10mg; prefer pravastatin.'),
('verapamil','colchicine','major','Verapamil inhibits P-gp, raising colchicine — fatal toxicity possible.','Avoid. Reduce colchicine dose if combination unavoidable.'),
('spironolactone','ACE inhibitor','major','Both raise potassium — hyperkalemia risk especially in elderly.','Monitor potassium closely; use low doses.'),
('furosemide','aminoglycosides','major','Additive ototoxicity — permanent hearing loss.','Avoid. If essential, use lowest doses and monitor hearing.'),
('furosemide','lithium','moderate','Furosemide reduces lithium renal clearance.','Monitor lithium levels closely.'),
('hydrochlorothiazide','lithium','moderate','Thiazide raises lithium levels by reducing renal excretion.','Monitor lithium levels; reduce lithium dose.'),
('haloperidol','lithium','major','Combination rarely causes severe neurotoxicity, even at therapeutic levels.','Monitor closely for confusion, fever, extrapyramidal signs.'),
('clozapine','carbamazepine','major','Additive bone marrow suppression — serious agranulocytosis risk.','Avoid. This combination is generally contraindicated.'),
('clozapine','ciprofloxacin','moderate','Ciprofloxacin inhibits CYP1A2, raising clozapine levels.','Monitor for toxicity; consider dose reduction.'),
('olanzapine','fluvoxamine','major','Fluvoxamine markedly raises olanzapine levels.','Reduce olanzapine dose by 33%; monitor for toxicity.'),
('fluoxetine','carbamazepine','moderate','Fluoxetine inhibits carbamazepine metabolism.','Monitor carbamazepine levels.'),
('fluoxetine','codeine','moderate','Fluoxetine inhibits CYP2D6, blocking codeine conversion to morphine.','Codeine analgesia may be inadequate. Use alternative opioid.'),
('paroxetine','tamoxifen','major','Paroxetine inhibits CYP2D6, blocking tamoxifen activation — treatment failure.','Avoid. Use sertraline or venlafaxine instead.'),
('sertraline','MAO inhibitor','major','Hypertensive crisis and serotonin syndrome — potentially fatal.','At least 14-day washout between MAO inhibitors and sertraline.'),
('amitriptyline','MAO inhibitor','major','Hypertensive crisis and hyperpyrexia — can be fatal.','Contraindicated. 14-day washout required.'),
('amitriptyline','tramadol','major','Serotonin syndrome and lowered seizure threshold.','Avoid combination if possible.'),
('alprazolam','itraconazole','major','Itraconazole inhibits CYP3A4, raising alprazolam 2-3x.','Reduce alprazolam dose by 50-75%; monitor sedation.'),
('carbamazepine','valproate','moderate','Variable interaction; carbamazepine reduces valproate levels.','Monitor both drug levels; adjust doses.'),
('valproate','lamotrigine','moderate','Valproate doubles lamotrigine half-life — toxicity risk.','Halve lamotrigine dose when adding valproate.'),
('phenobarbitone','warfarin','major','Phenobarbitone induces CYP2C9, reducing warfarin levels.','Increase warfarin dose; monitor INR closely.'),
('glibenclamide','ciprofloxacin','major','Ciprofloxacin potentiates hypoglycaemia from sulphonylureas.','Monitor blood glucose closely. Reduce sulphonylurea if needed.'),
('glipizide','fluconazole','major','Fluconazole raises glipizide levels — severe hypoglycaemia.','Monitor glucose closely; reduce glipizide dose.'),
('insulin','beta blocker','moderate','Beta-blockers mask hypoglycaemia symptoms; also delay recovery.','Prefer cardioselective beta-blocker; monitor glucose carefully.'),
('insulin','corticosteroids','major','Corticosteroids raise blood glucose, opposing insulin.','Monitor glucose frequently; increase insulin dose as needed.'),
('pioglitazone','gemfibrozil','major','Gemfibrozil inhibits pioglitazone metabolism — fluid retention, heart failure.','Avoid. If necessary, monitor for oedema and weight gain.'),
('celecoxib','warfarin','moderate','Celecoxib inhibits CYP2C9, raising warfarin levels.','Monitor INR when starting or stopping celecoxib.'),
('ibuprofen','ACE inhibitor','moderate','NSAIDs blunt antihypertensive effect and cause AKI in at-risk patients.','Avoid regular NSAID use with ACE inhibitors.'),
('codeine','MAO inhibitor','major','Agitation, coma, and hyperthermia — serotonin syndrome.','Contraindicated. 14-day washout needed.'),
('tramadol','MAO inhibitor','major','Serotonin syndrome — potentially fatal.','Contraindicated. 14-day washout required.'),
('morphine','MAO inhibitor','major','Excitation, hyperpyrexia, cardiovascular instability.','Avoid. Contraindicated combination.'),
('fentanyl','itraconazole','major','Itraconazole inhibits CYP3A4, raising fentanyl levels — respiratory depression.','Avoid. Reduce fentanyl dose significantly if necessary.'),
('simvastatin','gemfibrozil','major','Gemfibrozil raises simvastatin AUC 2-3 fold — rhabdomyolysis.','Contraindicated. Avoid combination.'),
('atorvastatin','gemfibrozil','major','Gemfibrozil raises atorvastatin levels — rhabdomyolysis risk.','Avoid. If fibrate needed, use fenofibrate.'),
('cyclosporine','NSAIDs','major','Additive nephrotoxicity.','Avoid NSAIDs. Use paracetamol.'),
('cyclosporine','simvastatin','major','Cyclosporine inhibits CYP3A4 — statin levels increase massively.','Contraindicated with simvastatin. Max pravastatin 20mg.'),
('cyclosporine','ketoconazole','major','Ketoconazole raises cyclosporine levels 3-fold.','Monitor cyclosporine levels. Reduce dose by 50-80%.'),
('cyclosporine','rifampicin','major','Rifampicin reduces cyclosporine levels by 80% — rejection risk.','Avoid. Use rifabutin if TB treatment needed.'),
('tacrolimus','fluconazole','major','Fluconazole inhibits CYP3A4, raising tacrolimus levels.','Reduce tacrolimus dose; monitor levels closely.'),
('levothyroxine','antacid','moderate','Aluminium antacids reduce levothyroxine absorption.','Separate by 4 hours.'),
('carbimazole','warfarin','major','Antithyroid drugs reduce warfarin requirements.','Monitor INR closely; significant dose reduction likely.'),
('omeprazole','methotrexate','moderate','PPIs reduce methotrexate renal excretion.','Monitor for methotrexate toxicity.'),
('ondansetron','amiodarone','major','Both prolong QT interval.','Avoid. Risk of torsades.'),
('domperidone','amiodarone','major','Both prolong QT interval — serious arrhythmia risk.','Avoid. Use metoclopramide cautiously instead.'),
('domperidone','fluconazole','major','Fluconazole raises domperidone levels — QT prolongation.','Contraindicated. Avoid combination.'),
('domperidone','erythromycin','major','Additive QT prolongation.','Avoid. Choose alternative antiemetic.'),
('misoprostol','oxytocin','major','Additive uterotonic effect — uterine hyperstimulation.','Do not use together. Serious obstetric risk.'),
('chloroquine','amiodarone','major','Both prolong QT interval.','Avoid combination.'),
('quinine','digoxin','major','Quinine inhibits P-glycoprotein, raising digoxin 2-fold.','Reduce digoxin dose by 50%; monitor levels.'),
('quinine','amiodarone','major','Both prolong QT interval.','Avoid. Serious risk of fatal arrhythmia.'),
('rivaroxaban','ketoconazole','major','Ketoconazole inhibits CYP3A4 and P-gp, raising rivaroxaban 2.6-fold.','Avoid azole antifungals with rivaroxaban.'),
('rivaroxaban','rifampicin','major','Rifampicin reduces rivaroxaban AUC by 50%.','Avoid combination. Serious risk of thrombosis.'),
('heparin','NSAIDs','major','Additive anticoagulant effect and GI bleeding.','Avoid NSAIDs during heparin therapy.'),
('sildenafil','alpha blocker','major','Additive hypotension — syncope and falls.','Start with low alpha-blocker dose; avoid same-time administration.'),
('tadalafil','nitrate','major','Potentially fatal hypotension.','Absolutely contraindicated.'),
('colchicine','clarithromycin','major','Clarithromycin inhibits P-gp/CYP3A4 — fatal colchicine toxicity.','Reduce colchicine dose or stop during antibiotics.'),
('allopurinol','azathioprine','major','Allopurinol inhibits xanthine oxidase — azathioprine toxicity.','Reduce azathioprine dose by 75%. Monitor blood counts.'),
('allopurinol','mercaptopurine','major','Same mechanism as azathioprine — bone marrow toxicity.','Reduce mercaptopurine dose by 75%.'),
('allopurinol','warfarin','moderate','Allopurinol inhibits warfarin metabolism.','Monitor INR; may need dose reduction.'),
('allopurinol','ampicillin','moderate','Additive rash risk (up to 20% of patients).','Use alternative antibiotic. Warn patients.'),
('theophylline','cimetidine','major','Cimetidine inhibits CYP1A2 — theophylline toxicity.','Use ranitidine instead of cimetidine. Monitor theophylline.'),
('salbutamol','non-selective beta-blocker','major','Non-selective beta-blockers oppose salbutamol bronchodilation.','Avoid propranolol and sotalol in asthma. Use cardioselective.'),
('pregabalin','opioids','major','Additive respiratory depression.','Use with caution; reduce opioid dose.'),
('gabapentin','opioids','major','Additive respiratory depression and sedation.','Use with caution; reduce opioid dose; monitor respiratory rate.'),
('pantoprazole','atazanavir','major','PPIs reduce atazanavir absorption almost completely.','Contraindicated. Avoid PPIs with atazanavir.'),
('vitamin E','warfarin','moderate','High-dose vitamin E may increase anticoagulant effect.','Monitor INR if patient starts high-dose vitamin E.'),
('grapefruit juice','simvastatin','major','Grapefruit inhibits CYP3A4 — large statin level increase.','Avoid grapefruit juice with statins.'),
('linezolid','serotonergic drugs','major','Linezolid is an MAO inhibitor — serotonin syndrome.','Avoid SSRIs, tramadol, pethidine with linezolid.'),
('vancomycin','aminoglycosides','major','Additive nephrotoxicity and ototoxicity.','Avoid if possible; monitor renal function daily.'),
('gentamicin','furosemide','major','Additive ototoxicity and nephrotoxicity.','Avoid. If essential, use lowest doses; monitor renal function.'),
('phenylephrine','MAO inhibitor','major','Severe hypertensive crisis.','Absolutely contraindicated.'),
('pseudoephedrine','MAO inhibitor','major','Severe hypertensive crisis.','Absolutely contraindicated.'),
('dextromethorphan','MAO inhibitor','major','Serotonin syndrome — potentially fatal.','Absolutely contraindicated.'),
('tramadol','ondansetron','moderate','Both serotonergic — serotonin syndrome risk; ondansetron blocks tramadol analgesia.','Use alternative antiemetic with tramadol.'),
('terbinafine','warfarin','moderate','Terbinafine inhibits CYP2C9, raising warfarin levels.','Monitor INR closely during terbinafine course.'),
('nifedipine','rifampicin','major','Rifampicin reduces nifedipine levels by 90% — ineffective.','Increase dose substantially or use non-CYP3A4 antihypertensive.'),
('losartan','potassium supplement','major','Both raise potassium — hyperkalemia risk.','Monitor potassium closely. Avoid routine supplementation.'),
('glimepiride','clarithromycin','major','Clarithromycin inhibits CYP3A4 — sulphonylurea toxicity.','Monitor glucose; reduce glimepiride dose.'),
('celecoxib','fluconazole','major','Fluconazole inhibits CYP2C9, raising celecoxib levels 2-fold.','Reduce celecoxib dose; monitor for toxicity.'),
('colestyramine','warfarin','major','Colestyramine reduces warfarin absorption.','Give warfarin at least 6 hours after colestyramine.'),
('colestyramine','levothyroxine','major','Colestyramine reduces levothyroxine absorption.','Give levothyroxine at least 4 hours before colestyramine.'),
('lithium','ACE inhibitor','major','ACE inhibitors raise lithium levels — toxicity.','Reduce lithium dose; monitor levels closely.'),
('carbamazepine','erythromycin','major','Erythromycin inhibits CYP3A4 — carbamazepine toxicity.','Avoid. Monitor carbamazepine levels if unavoidable.'),
('valproate','carbapenems','major','Carbapenems reduce valproate levels by 60-100% — seizure risk.','Avoid combination. Valproate becomes subtherapeutic.'),
('phenytoin','rifampicin','major','Rifampicin induces CYP2C9/3A4 — phenytoin levels drop.','Monitor phenytoin levels; dose increase required.'),
('warfarin','amiodarone','major','Amiodarone inhibits CYP2C9 — INR rises dangerously.','Reduce warfarin by 30-50%; monitor INR weekly for months.'),
('warfarin','clarithromycin','major','Clarithromycin inhibits warfarin metabolism.','Reduce warfarin; monitor INR daily.'),
('warfarin','simvastatin','moderate','Simvastatin may modestly increase anticoagulant effect.','Monitor INR when starting or stopping simvastatin.'),
('warfarin','tamoxifen','major','Tamoxifen inhibits CYP2C9 — warfarin levels rise dramatically.','Reduce warfarin dose by 20-30%; monitor INR weekly.'),
-- Additional pairs for 245+ total
('amlodipine','simvastatin','moderate','Amlodipine inhibits CYP3A4; do not exceed simvastatin 20mg.','Use rosuvastatin or pravastatin as alternatives.'),
('amlodipine','tacrolimus','moderate','Amlodipine inhibits CYP3A4, raising tacrolimus levels.','Monitor tacrolimus levels closely.'),
('clarithromycin','midazolam','major','Clarithromycin inhibits CYP3A4, raising midazolam >5-fold.','Avoid oral midazolam. Use temazepam.'),
('clarithromycin','simvastatin','major','Clarithromycin inhibits CYP3A4 — rhabdomyolysis.','Suspend statin during clarithromycin course.'),
('clarithromycin','cisapride','major','Both prolong QT interval — fatal arrhythmia.','Contraindicated.'),
('ketoconazole','buspirone','major','Ketoconazole raises buspirone 13-fold.','Reduce buspirone dose by 90% or use alternative anxiolytic.'),
('ketoconazole','midazolam','major','Ketoconazole inhibits CYP3A4 — midazolam levels rise 15-fold.','Avoid combination. Use lorazepam.'),
('metformin','contrast media','major','IV iodinated contrast can cause lactic acidosis in patients on metformin.','Withhold metformin 48 hours before and after IV contrast.'),
('metformin','alcohol','moderate','Alcohol potentiates lactic acidosis risk with metformin.','Advise to limit alcohol. Avoid binge drinking.'),
('metformin','trimethoprim','moderate','Trimethoprim raises metformin levels — hypoglycaemia.','Monitor blood glucose during antibiotic course.'),
('digoxin','amiodarone','major','Amiodarone inhibits P-gp, raising digoxin levels 70-100%.','Reduce digoxin dose by 50%; monitor levels closely.'),
('digoxin','verapamil','major','Verapamil inhibits P-gp, raising digoxin levels.','Reduce digoxin dose by 33-50%; monitor levels.'),
('digoxin','spironolactone','moderate','Spironolactone may falsely raise digoxin assay and cause toxicity.','Monitor digoxin levels and ECG.'),
('digoxin','azithromycin','moderate','Azithromycin inhibits P-gp, raising digoxin levels.','Monitor digoxin levels during azithromycin course.'),
('lithium','NSAIDs','major','NSAIDs reduce renal lithium clearance — toxicity.','Avoid NSAIDs. Use paracetamol.'),
('lithium','diuretics','major','Thiazide and loop diuretics raise lithium levels.','Monitor lithium levels closely; reduce dose.'),
('lithium','sodium restriction','major','Low sodium diet raises lithium levels — toxicity.','Maintain consistent sodium intake; monitor levels.'),
('warfarin','fluconazole','major','Fluconazole strongly inhibits CYP2C9 — INR 2-4x rise.','Reduce warfarin by 25-50%; monitor INR daily.'),
('warfarin','metronidazole','major','Metronidazole inhibits CYP2C9 and CYP3A4 — INR elevation.','Reduce warfarin; monitor INR every 1-2 days.'),
('warfarin','omeprazole','moderate','Omeprazole inhibits CYP2C19, modestly raising S-warfarin.','Monitor INR when starting or stopping omeprazole.'),
('warfarin','aspirin','major','Additive antiplatelet + anticoagulant effect — serious GI bleeding.','Avoid combination. Use PPI if combination unavoidable.'),
('warfarin','carbamazepine','major','Carbamazepine induces CYP2C9 — warfarin efficacy lost.','Increase warfarin dose substantially; monitor INR.'),
('warfarin','St Johns Wort','major','St Johns Wort induces CYP2C9 and P-gp — warfarin failure.','Avoid herbal supplements with warfarin.'),
('warfarin','clopidogrel','major','Dual antiplatelet and anticoagulant — major bleeding risk.','Use only when clinically essential. Monitor for bleeding.'),
('phenytoin','valproate','moderate','Valproate displaces phenytoin and inhibits metabolism — complex.','Monitor free phenytoin levels. Total levels misleading.'),
('phenytoin','cimetidine','moderate','Cimetidine inhibits phenytoin metabolism — toxicity.','Use ranitidine. Monitor phenytoin levels.'),
('phenytoin','fluconazole','major','Fluconazole raises phenytoin levels significantly.','Monitor phenytoin levels during antifungal treatment.'),
('carbamazepine','lithium','moderate','Combination raises neurotoxicity risk even at therapeutic levels.','Monitor carefully; reduce dose if neurotoxicity signs.'),
('carbamazepine','oral contraceptives','major','Carbamazepine induces CYP3A4 — contraceptive failure.','Use alternative contraception (non-hormonal or higher-dose OCP).'),
('carbamazepine','clozapine','major','Additive bone marrow suppression — agranulocytosis.','Avoid. This combination is generally contraindicated.'),
('carbamazepine','warfarin','major','Carbamazepine induces CYP2C9 — warfarin levels drop.','Increase warfarin dose; monitor INR closely.'),
('lamotrigine','oral contraceptives','major','Combined OCP reduces lamotrigine levels by 50% — seizure risk.','Increase lamotrigine dose during OCP use.'),
('sodium valproate','aspirin','moderate','Aspirin displaces valproate from protein binding.','Monitor valproate levels; reduce aspirin dose.'),
('levodopa','MAO inhibitor','major','Hypertensive crisis — potentially fatal.','Contraindicated. Use selective MAO-B inhibitor with caution.'),
('selegiline','SSRIs','major','Selegiline + SSRIs can cause serotonin syndrome.','Avoid combination. 14-day washout needed.'),
('haloperidol','anticholinergics','moderate','Additive anticholinergic effect — confusion, urinary retention.','Reduce doses; monitor in elderly.'),
('risperidone','carbamazepine','major','Carbamazepine induces risperidone metabolism — reduced efficacy.','Increase risperidone dose; monitor response.'),
('quetiapine','carbamazepine','major','Carbamazepine reduces quetiapine by 87%.','Avoid. Increase quetiapine 5-fold if unavoidable.'),
('aripiprazole','fluoxetine','moderate','Fluoxetine inhibits CYP2D6, raising aripiprazole levels.','Reduce aripiprazole dose by 50%.'),
('methylphenidate','MAO inhibitor','major','Hypertensive crisis.','Contraindicated. 14-day washout required.'),
('methylphenidate','warfarin','moderate','Methylphenidate inhibits warfarin metabolism.','Monitor INR; reduce warfarin dose if needed.'),
('clonidine','beta blocker','major','Rebound hypertension on withdrawal; both cause bradycardia.','Do not stop clonidine abruptly. Taper gradually.'),
('amlodipine','rifampicin','major','Rifampicin reduces amlodipine levels by 90%.','Increase dose or switch to non-CYP3A4 antihypertensive.'),
('atenolol','verapamil','major','Additive bradycardia and heart block — cardiac arrest risk.','Avoid IV combination. Oral with ECG monitoring.'),
('bisoprolol','diltiazem','major','Additive bradycardia and AV block.','Avoid combination. ECG monitoring required.'),
('lisinopril','spironolactone','major','Both raise potassium — severe hyperkalemia.','Monitor potassium closely; avoid potassium supplements.'),
('enalapril','potassium','major','ACE inhibitor + potassium supplementation — hyperkalemia.','Avoid routine potassium supplements with ACE inhibitors.'),
('amlodipine','cyclosporine','moderate','Cyclosporine raises amlodipine levels modestly.','Monitor blood pressure and cyclosporine levels.'),
('rosuvastatin','cyclosporine','major','Cyclosporine inhibits OATP1B1, raising rosuvastatin levels.','Maximum rosuvastatin 5mg with cyclosporine.'),
('rosuvastatin','gemfibrozil','moderate','Gemfibrozil inhibits rosuvastatin transport — modest level rise.','Maximum rosuvastatin 10mg with gemfibrozil.'),
('nifedipine','tacrolimus','moderate','Nifedipine inhibits CYP3A4, raising tacrolimus.','Monitor tacrolimus levels closely.'),
('esomeprazole','clopidogrel','major','Esomeprazole inhibits CYP2C19, blocking clopidogrel activation.','Use pantoprazole or ranitidine instead.'),
('omeprazole','clopidogrel','major','Omeprazole inhibits CYP2C19, reducing clopidogrel efficacy.','Prefer pantoprazole for GI protection with clopidogrel.'),
('alendronate','NSAIDs','moderate','Additive GI irritation and ulcer risk.','Separate doses; use PPI for GI protection.'),
('alendronate','calcium','major','Calcium reduces alendronate absorption by 60%.','Take alendronate on empty stomach; calcium at least 30 min later.'),
('prednisolone','ibuprofen','major','Additive GI ulcer risk.','Always co-prescribe PPI with steroid + NSAID combination.'),
('prednisolone','live vaccines','major','Immunosuppressive doses impair vaccine response; live vaccine risk.','Avoid live vaccines during steroid therapy.'),
('prednisolone','ketoconazole','moderate','Ketoconazole inhibits steroid metabolism — toxicity.','Reduce prednisolone dose; monitor for Cushingoid effects.'),
('dexamethasone','phenytoin','major','Phenytoin reduces dexamethasone levels by 50%.','Double dexamethasone dose; monitor response.'),
('hydrocortisone','rifampicin','major','Rifampicin reduces hydrocortisone efficacy — adrenal crisis risk.','Double hydrocortisone dose; monitor carefully.'),
('azathioprine','ACE inhibitor','moderate','Additive bone marrow suppression.','Monitor blood counts closely.'),
('methotrexate','NSAIDs','major','NSAIDs reduce methotrexate renal clearance — toxicity.','Avoid NSAIDs. Use paracetamol. Monitor methotrexate levels.'),
('methotrexate','cotrimoxazole','major','Additive folate antagonism — severe bone marrow suppression.','Absolutely contraindicated.'),
('cyclophosphamide','allopurinol','moderate','Allopurinol inhibits cyclophosphamide metabolism — bone marrow toxicity.','Monitor blood counts carefully.'),
('tamoxifen','CYP2D6 inhibitors','major','Strong CYP2D6 inhibitors (fluoxetine, paroxetine) block tamoxifen activation.','Avoid SSRIs that inhibit CYP2D6 during tamoxifen therapy.'),
('anastrozole','tamoxifen','major','Tamoxifen reduces anastrozole levels by 30% — reduced efficacy.','Avoid combination.'),
('imatinib','ketoconazole','major','Ketoconazole inhibits CYP3A4, raising imatinib levels.','Reduce imatinib dose or use alternative antifungal.'),
('imatinib','rifampicin','major','Rifampicin reduces imatinib levels by 74%.','Avoid combination.'),
('dasatinib','antacids','moderate','Antacids raise gastric pH, reducing dasatinib absorption.','Separate by 2 hours.'),
('erlotinib','proton pump inhibitors','major','PPIs raise gastric pH, reducing erlotinib absorption significantly.','Avoid PPIs with erlotinib. Use H2 blockers if needed.'),
('hydroxychloroquine','tamoxifen','major','Both prolong QT interval.','ECG monitoring required.'),
('hydroxychloroquine','digoxin','moderate','Hydroxychloroquine raises digoxin levels.','Monitor digoxin levels during co-administration.'),
('chlorpromazine','lithium','moderate','Phenothiazines may mask lithium toxicity signs.','Monitor lithium levels; use cautiously.'),
('mirtazapine','tramadol','major','Additive serotonergic effects — serotonin syndrome.','Avoid combination.'),
('bupropion','MAO inhibitor','major','Hypertensive crisis.','14-day washout required.'),
('bupropion','valproate','moderate','Bupropion lowers seizure threshold.','Avoid in patients with seizure disorders.'),
('venlafaxine','MAO inhibitor','major','Serotonin syndrome — potentially fatal.','14-day washout required.'),
('atomoxetine','MAO inhibitor','major','Hypertensive crisis.','14-day washout required.'),
('donepezil','succinylcholine','major','Cholinesterase inhibitor prolongs succinylcholine blockade.','Warn anaesthetist; monitor closely.'),
('finasteride','warfarin','minor','Finasteride modestly raises warfarin levels.','Monitor INR if warfarin started/stopped.'),
('dutasteride','amlodipine','minor','Minor CYP3A4 interaction — modest dutasteride level rise.','No dose change usually needed.'),
('terbinafine','amitriptyline','major','Terbinafine inhibits CYP2D6 — tricyclic toxicity.','Reduce amitriptyline dose; monitor for toxicity.'),
('terbinafine','codeine','moderate','Terbinafine inhibits CYP2D6 — blocks codeine activation.','Codeine analgesia may fail; use alternative opioid.'),
('ivermectin','warfarin','moderate','Ivermectin may potentiate warfarin.','Monitor INR after ivermectin use.'),
('albendazole','cimetidine','moderate','Cimetidine raises albendazole levels — increased efficacy and toxicity.','Reduce albendazole dose; monitor liver function.'),
('praziquantel','rifampicin','major','Rifampicin reduces praziquantel levels — treatment failure.','Avoid combination.'),
('quinine','rifampicin','major','Rifampicin reduces quinine levels significantly.','Avoid combination.'),
('doxycycline','antacids','major','Aluminium/calcium antacids reduce doxycycline absorption by 80%.','Separate by at least 3 hours.'),
('tetracycline','iron','major','Iron reduces tetracycline absorption by 50-80%.','Separate by 3 hours.'),
('ciprofloxacin','theophylline','major','Ciprofloxacin inhibits CYP1A2, raising theophylline to toxic levels.','Reduce theophylline dose by 30-50%; monitor levels.'),
('levofloxacin','NSAIDs','moderate','NSAIDs increase seizure risk with fluoroquinolones.','Avoid NSAIDs. Use paracetamol.'),
('linezolid','tyramine-rich foods','major','Linezolid inhibits MAO — tyramine-rich food causes hypertensive crisis.','Avoid aged cheese, pickled fish, red wine, broad beans.'),
('rifampicin','methadone','major','Rifampicin reduces methadone levels by 50-75% — withdrawal.','Increase methadone dose substantially. Monitor closely.'),
('buprenorphine','benzodiazepines','major','Additive respiratory depression — deaths reported.','Avoid combination; if essential, use lowest doses with monitoring.'),
('naltrexone','opioids','major','Naltrexone blocks opioid effect — withdrawal precipitated.','Do not use in opioid-dependent patients. 7-day washout needed.'),
('acetazolamide','aspirin','major','Acetazolamide raises aspirin toxicity by ion trapping.','Avoid high-dose aspirin with acetazolamide.'),
('colchicine','statins','major','Additive myopathy risk, especially with cyclosporine.','Monitor for muscle pain and weakness.'),
('probenecid','NSAIDs','moderate','NSAIDs blunt uricosuric effect of probenecid.','Avoid NSAIDs during probenecid therapy.'),
('allopurinol','ACE inhibitor','moderate','Additive hypersensitivity reactions reported.','Monitor; avoid in renal impairment.');
